version: "3.9"

services:
  db:
    image: postgres:15
    container_name: devops_tasks_db
    environment:
      POSTGRES_DB: tasksdb
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - devops_net

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: devops_tasks_backend
    environment:
      PORT: 3000
      # On met déjà une DATABASE_URL pour la suite (même si non utilisée pour l'instant)
      DATABASE_URL: postgres://devops:devops@db:5432/tasksdb
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - devops_net

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    container_name: devops_tasks_frontend
    environment:
      # Le frontend utilisera cette URL pour appeler le backend
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - devops_net

volumes:
  db_data:

networks:
  devops_net:
    driver: bridge
