apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: devops-tasks
    tier: frontend
  ports:
    - name: http
      port: 5173
      targetPort: 5173
  type: NodePort