apiVersion: v1
kind: Secret
metadata:
  name: devops-tasks-secret
type: Opaque
stringData:
  POSTGRES_USER: "devops"
  POSTGRES_PASSWORD: "devops"
  DATABASE_URL: "postgres://devops:devops@postgres-service:5432/tasksdb"